package sdk.duelyst.console.message;

public enum MessageType {
	CANCEL, CARD_DRAW, CARD_PLAY, CARD_REPLACE, DECK_UPDATE, EXIT, JOINED_GAME, GAME_END, GAME_START, GAUNTLET_OPTIONS, STARTING_HAND, TURN_END
}
